/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRankingRouteImport } from './routes/_authenticated/ranking'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated/perfil'
import { Route as AuthenticatedNovaMetaRouteImport } from './routes/_authenticated/nova-meta'
import { Route as AuthenticatedNotificacoesRouteImport } from './routes/_authenticated/notificacoes'
import { Route as AuthenticatedMetasRouteImport } from './routes/_authenticated/metas'
import { Route as AuthenticatedFeedRouteImport } from './routes/_authenticated/feed'
import { Route as AuthenticatedDuelosRouteImport } from './routes/_authenticated/duelos'
import { Route as AuthenticatedBuscaRouteImport } from './routes/_authenticated/busca'
import { Route as AuthenticatedPerfilEditarRouteImport } from './routes/_authenticated/perfil.editar'
import { Route as AuthenticatedMetaIdRouteImport } from './routes/_authenticated/meta.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRankingRoute = AuthenticatedRankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNovaMetaRoute = AuthenticatedNovaMetaRouteImport.update({
  id: '/nova-meta',
  path: '/nova-meta',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificacoesRoute =
  AuthenticatedNotificacoesRouteImport.update({
    id: '/notificacoes',
    path: '/notificacoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMetasRoute = AuthenticatedMetasRouteImport.update({
  id: '/metas',
  path: '/metas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFeedRoute = AuthenticatedFeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDuelosRoute = AuthenticatedDuelosRouteImport.update({
  id: '/duelos',
  path: '/duelos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBuscaRoute = AuthenticatedBuscaRouteImport.update({
  id: '/busca',
  path: '/busca',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPerfilEditarRoute =
  AuthenticatedPerfilEditarRouteImport.update({
    id: '/editar',
    path: '/editar',
    getParentRoute: () => AuthenticatedPerfilRoute,
  } as any)
const AuthenticatedMetaIdRoute = AuthenticatedMetaIdRouteImport.update({
  id: '/meta/$id',
  path: '/meta/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/busca': typeof AuthenticatedBuscaRoute
  '/duelos': typeof AuthenticatedDuelosRoute
  '/feed': typeof AuthenticatedFeedRoute
  '/metas': typeof AuthenticatedMetasRoute
  '/notificacoes': typeof AuthenticatedNotificacoesRoute
  '/nova-meta': typeof AuthenticatedNovaMetaRoute
  '/perfil': typeof AuthenticatedPerfilRouteWithChildren
  '/ranking': typeof AuthenticatedRankingRoute
  '/meta/$id': typeof AuthenticatedMetaIdRoute
  '/perfil/editar': typeof AuthenticatedPerfilEditarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/busca': typeof AuthenticatedBuscaRoute
  '/duelos': typeof AuthenticatedDuelosRoute
  '/feed': typeof AuthenticatedFeedRoute
  '/metas': typeof AuthenticatedMetasRoute
  '/notificacoes': typeof AuthenticatedNotificacoesRoute
  '/nova-meta': typeof AuthenticatedNovaMetaRoute
  '/perfil': typeof AuthenticatedPerfilRouteWithChildren
  '/ranking': typeof AuthenticatedRankingRoute
  '/meta/$id': typeof AuthenticatedMetaIdRoute
  '/perfil/editar': typeof AuthenticatedPerfilEditarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/busca': typeof AuthenticatedBuscaRoute
  '/_authenticated/duelos': typeof AuthenticatedDuelosRoute
  '/_authenticated/feed': typeof AuthenticatedFeedRoute
  '/_authenticated/metas': typeof AuthenticatedMetasRoute
  '/_authenticated/notificacoes': typeof AuthenticatedNotificacoesRoute
  '/_authenticated/nova-meta': typeof AuthenticatedNovaMetaRoute
  '/_authenticated/perfil': typeof AuthenticatedPerfilRouteWithChildren
  '/_authenticated/ranking': typeof AuthenticatedRankingRoute
  '/_authenticated/meta/$id': typeof AuthenticatedMetaIdRoute
  '/_authenticated/perfil/editar': typeof AuthenticatedPerfilEditarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/busca'
    | '/duelos'
    | '/feed'
    | '/metas'
    | '/notificacoes'
    | '/nova-meta'
    | '/perfil'
    | '/ranking'
    | '/meta/$id'
    | '/perfil/editar'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/busca'
    | '/duelos'
    | '/feed'
    | '/metas'
    | '/notificacoes'
    | '/nova-meta'
    | '/perfil'
    | '/ranking'
    | '/meta/$id'
    | '/perfil/editar'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/busca'
    | '/_authenticated/duelos'
    | '/_authenticated/feed'
    | '/_authenticated/metas'
    | '/_authenticated/notificacoes'
    | '/_authenticated/nova-meta'
    | '/_authenticated/perfil'
    | '/_authenticated/ranking'
    | '/_authenticated/meta/$id'
    | '/_authenticated/perfil/editar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/ranking': {
      id: '/_authenticated/ranking'
      path: '/ranking'
      fullPath: '/ranking'
      preLoaderRoute: typeof AuthenticatedRankingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/nova-meta': {
      id: '/_authenticated/nova-meta'
      path: '/nova-meta'
      fullPath: '/nova-meta'
      preLoaderRoute: typeof AuthenticatedNovaMetaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notificacoes': {
      id: '/_authenticated/notificacoes'
      path: '/notificacoes'
      fullPath: '/notificacoes'
      preLoaderRoute: typeof AuthenticatedNotificacoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/metas': {
      id: '/_authenticated/metas'
      path: '/metas'
      fullPath: '/metas'
      preLoaderRoute: typeof AuthenticatedMetasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/feed': {
      id: '/_authenticated/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof AuthenticatedFeedRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/duelos': {
      id: '/_authenticated/duelos'
      path: '/duelos'
      fullPath: '/duelos'
      preLoaderRoute: typeof AuthenticatedDuelosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/busca': {
      id: '/_authenticated/busca'
      path: '/busca'
      fullPath: '/busca'
      preLoaderRoute: typeof AuthenticatedBuscaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/perfil/editar': {
      id: '/_authenticated/perfil/editar'
      path: '/editar'
      fullPath: '/perfil/editar'
      preLoaderRoute: typeof AuthenticatedPerfilEditarRouteImport
      parentRoute: typeof AuthenticatedPerfilRoute
    }
    '/_authenticated/meta/$id': {
      id: '/_authenticated/meta/$id'
      path: '/meta/$id'
      fullPath: '/meta/$id'
      preLoaderRoute: typeof AuthenticatedMetaIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedPerfilRouteChildren {
  AuthenticatedPerfilEditarRoute: typeof AuthenticatedPerfilEditarRoute
}

const AuthenticatedPerfilRouteChildren: AuthenticatedPerfilRouteChildren = {
  AuthenticatedPerfilEditarRoute: AuthenticatedPerfilEditarRoute,
}

const AuthenticatedPerfilRouteWithChildren =
  AuthenticatedPerfilRoute._addFileChildren(AuthenticatedPerfilRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedBuscaRoute: typeof AuthenticatedBuscaRoute
  AuthenticatedDuelosRoute: typeof AuthenticatedDuelosRoute
  AuthenticatedFeedRoute: typeof AuthenticatedFeedRoute
  AuthenticatedMetasRoute: typeof AuthenticatedMetasRoute
  AuthenticatedNotificacoesRoute: typeof AuthenticatedNotificacoesRoute
  AuthenticatedNovaMetaRoute: typeof AuthenticatedNovaMetaRoute
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRouteWithChildren
  AuthenticatedRankingRoute: typeof AuthenticatedRankingRoute
  AuthenticatedMetaIdRoute: typeof AuthenticatedMetaIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedBuscaRoute: AuthenticatedBuscaRoute,
  AuthenticatedDuelosRoute: AuthenticatedDuelosRoute,
  AuthenticatedFeedRoute: AuthenticatedFeedRoute,
  AuthenticatedMetasRoute: AuthenticatedMetasRoute,
  AuthenticatedNotificacoesRoute: AuthenticatedNotificacoesRoute,
  AuthenticatedNovaMetaRoute: AuthenticatedNovaMetaRoute,
  AuthenticatedPerfilRoute: AuthenticatedPerfilRouteWithChildren,
  AuthenticatedRankingRoute: AuthenticatedRankingRoute,
  AuthenticatedMetaIdRoute: AuthenticatedMetaIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
