/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRankingRouteImport } from './routes/_authenticated/ranking'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated/perfil'
import { Route as AuthenticatedNovaMetaRouteImport } from './routes/_authenticated/nova-meta'
import { Route as AuthenticatedNotificacoesRouteImport } from './routes/_authenticated/notificacoes'
import { Route as AuthenticatedMetasRouteImport } from './routes/_authenticated/metas'
import { Route as AuthenticatedFeedRouteImport } from './routes/_authenticated/feed'
import { Route as AuthenticatedDuelosRouteImport } from './routes/_authenticated/duelos'
import { Route as AuthenticatedDescobrirRouteImport } from './routes/_authenticated/descobrir'
import { Route as AuthenticatedDesafioTemporadaRouteImport } from './routes/_authenticated/desafio-temporada'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedBuscaRouteImport } from './routes/_authenticated/busca'
import { Route as AuthenticatedEquipesIndexRouteImport } from './routes/_authenticated/equipes.index'
import { Route as AuthenticatedPerfilEditarRouteImport } from './routes/_authenticated/perfil_.editar'
import { Route as AuthenticatedMetaIdRouteImport } from './routes/_authenticated/meta.$id'
import { Route as AuthenticatedEquipesNovaRouteImport } from './routes/_authenticated/equipes.nova'
import { Route as AuthenticatedEquipesIdIndexRouteImport } from './routes/_authenticated/equipes.$id.index'
import { Route as AuthenticatedEquipesIdDesafioNovoRouteImport } from './routes/_authenticated/equipes.$id.desafio.novo'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRankingRoute = AuthenticatedRankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNovaMetaRoute = AuthenticatedNovaMetaRouteImport.update({
  id: '/nova-meta',
  path: '/nova-meta',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificacoesRoute =
  AuthenticatedNotificacoesRouteImport.update({
    id: '/notificacoes',
    path: '/notificacoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMetasRoute = AuthenticatedMetasRouteImport.update({
  id: '/metas',
  path: '/metas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFeedRoute = AuthenticatedFeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDuelosRoute = AuthenticatedDuelosRouteImport.update({
  id: '/duelos',
  path: '/duelos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDescobrirRoute = AuthenticatedDescobrirRouteImport.update({
  id: '/descobrir',
  path: '/descobrir',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDesafioTemporadaRoute =
  AuthenticatedDesafioTemporadaRouteImport.update({
    id: '/desafio-temporada',
    path: '/desafio-temporada',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBuscaRoute = AuthenticatedBuscaRouteImport.update({
  id: '/busca',
  path: '/busca',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEquipesIndexRoute =
  AuthenticatedEquipesIndexRouteImport.update({
    id: '/equipes/',
    path: '/equipes/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPerfilEditarRoute =
  AuthenticatedPerfilEditarRouteImport.update({
    id: '/perfil_/editar',
    path: '/perfil/editar',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMetaIdRoute = AuthenticatedMetaIdRouteImport.update({
  id: '/meta/$id',
  path: '/meta/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEquipesNovaRoute =
  AuthenticatedEquipesNovaRouteImport.update({
    id: '/equipes/nova',
    path: '/equipes/nova',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEquipesIdIndexRoute =
  AuthenticatedEquipesIdIndexRouteImport.update({
    id: '/equipes/$id/',
    path: '/equipes/$id/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEquipesIdDesafioNovoRoute =
  AuthenticatedEquipesIdDesafioNovoRouteImport.update({
    id: '/equipes/$id/desafio/novo',
    path: '/equipes/$id/desafio/novo',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/busca': typeof AuthenticatedBuscaRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/desafio-temporada': typeof AuthenticatedDesafioTemporadaRoute
  '/descobrir': typeof AuthenticatedDescobrirRoute
  '/duelos': typeof AuthenticatedDuelosRoute
  '/feed': typeof AuthenticatedFeedRoute
  '/metas': typeof AuthenticatedMetasRoute
  '/notificacoes': typeof AuthenticatedNotificacoesRoute
  '/nova-meta': typeof AuthenticatedNovaMetaRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/ranking': typeof AuthenticatedRankingRoute
  '/equipes/nova': typeof AuthenticatedEquipesNovaRoute
  '/meta/$id': typeof AuthenticatedMetaIdRoute
  '/perfil/editar': typeof AuthenticatedPerfilEditarRoute
  '/equipes/': typeof AuthenticatedEquipesIndexRoute
  '/equipes/$id/': typeof AuthenticatedEquipesIdIndexRoute
  '/equipes/$id/desafio/novo': typeof AuthenticatedEquipesIdDesafioNovoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/busca': typeof AuthenticatedBuscaRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/desafio-temporada': typeof AuthenticatedDesafioTemporadaRoute
  '/descobrir': typeof AuthenticatedDescobrirRoute
  '/duelos': typeof AuthenticatedDuelosRoute
  '/feed': typeof AuthenticatedFeedRoute
  '/metas': typeof AuthenticatedMetasRoute
  '/notificacoes': typeof AuthenticatedNotificacoesRoute
  '/nova-meta': typeof AuthenticatedNovaMetaRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/ranking': typeof AuthenticatedRankingRoute
  '/equipes/nova': typeof AuthenticatedEquipesNovaRoute
  '/meta/$id': typeof AuthenticatedMetaIdRoute
  '/perfil/editar': typeof AuthenticatedPerfilEditarRoute
  '/equipes': typeof AuthenticatedEquipesIndexRoute
  '/equipes/$id': typeof AuthenticatedEquipesIdIndexRoute
  '/equipes/$id/desafio/novo': typeof AuthenticatedEquipesIdDesafioNovoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/busca': typeof AuthenticatedBuscaRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/desafio-temporada': typeof AuthenticatedDesafioTemporadaRoute
  '/_authenticated/descobrir': typeof AuthenticatedDescobrirRoute
  '/_authenticated/duelos': typeof AuthenticatedDuelosRoute
  '/_authenticated/feed': typeof AuthenticatedFeedRoute
  '/_authenticated/metas': typeof AuthenticatedMetasRoute
  '/_authenticated/notificacoes': typeof AuthenticatedNotificacoesRoute
  '/_authenticated/nova-meta': typeof AuthenticatedNovaMetaRoute
  '/_authenticated/perfil': typeof AuthenticatedPerfilRoute
  '/_authenticated/ranking': typeof AuthenticatedRankingRoute
  '/_authenticated/equipes/nova': typeof AuthenticatedEquipesNovaRoute
  '/_authenticated/meta/$id': typeof AuthenticatedMetaIdRoute
  '/_authenticated/perfil_/editar': typeof AuthenticatedPerfilEditarRoute
  '/_authenticated/equipes/': typeof AuthenticatedEquipesIndexRoute
  '/_authenticated/equipes/$id/': typeof AuthenticatedEquipesIdIndexRoute
  '/_authenticated/equipes/$id/desafio/novo': typeof AuthenticatedEquipesIdDesafioNovoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/busca'
    | '/configuracoes'
    | '/desafio-temporada'
    | '/descobrir'
    | '/duelos'
    | '/feed'
    | '/metas'
    | '/notificacoes'
    | '/nova-meta'
    | '/perfil'
    | '/ranking'
    | '/equipes/nova'
    | '/meta/$id'
    | '/perfil/editar'
    | '/equipes/'
    | '/equipes/$id/'
    | '/equipes/$id/desafio/novo'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/busca'
    | '/configuracoes'
    | '/desafio-temporada'
    | '/descobrir'
    | '/duelos'
    | '/feed'
    | '/metas'
    | '/notificacoes'
    | '/nova-meta'
    | '/perfil'
    | '/ranking'
    | '/equipes/nova'
    | '/meta/$id'
    | '/perfil/editar'
    | '/equipes'
    | '/equipes/$id'
    | '/equipes/$id/desafio/novo'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/busca'
    | '/_authenticated/configuracoes'
    | '/_authenticated/desafio-temporada'
    | '/_authenticated/descobrir'
    | '/_authenticated/duelos'
    | '/_authenticated/feed'
    | '/_authenticated/metas'
    | '/_authenticated/notificacoes'
    | '/_authenticated/nova-meta'
    | '/_authenticated/perfil'
    | '/_authenticated/ranking'
    | '/_authenticated/equipes/nova'
    | '/_authenticated/meta/$id'
    | '/_authenticated/perfil_/editar'
    | '/_authenticated/equipes/'
    | '/_authenticated/equipes/$id/'
    | '/_authenticated/equipes/$id/desafio/novo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/ranking': {
      id: '/_authenticated/ranking'
      path: '/ranking'
      fullPath: '/ranking'
      preLoaderRoute: typeof AuthenticatedRankingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/nova-meta': {
      id: '/_authenticated/nova-meta'
      path: '/nova-meta'
      fullPath: '/nova-meta'
      preLoaderRoute: typeof AuthenticatedNovaMetaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notificacoes': {
      id: '/_authenticated/notificacoes'
      path: '/notificacoes'
      fullPath: '/notificacoes'
      preLoaderRoute: typeof AuthenticatedNotificacoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/metas': {
      id: '/_authenticated/metas'
      path: '/metas'
      fullPath: '/metas'
      preLoaderRoute: typeof AuthenticatedMetasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/feed': {
      id: '/_authenticated/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof AuthenticatedFeedRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/duelos': {
      id: '/_authenticated/duelos'
      path: '/duelos'
      fullPath: '/duelos'
      preLoaderRoute: typeof AuthenticatedDuelosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/descobrir': {
      id: '/_authenticated/descobrir'
      path: '/descobrir'
      fullPath: '/descobrir'
      preLoaderRoute: typeof AuthenticatedDescobrirRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/desafio-temporada': {
      id: '/_authenticated/desafio-temporada'
      path: '/desafio-temporada'
      fullPath: '/desafio-temporada'
      preLoaderRoute: typeof AuthenticatedDesafioTemporadaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/busca': {
      id: '/_authenticated/busca'
      path: '/busca'
      fullPath: '/busca'
      preLoaderRoute: typeof AuthenticatedBuscaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/equipes/': {
      id: '/_authenticated/equipes/'
      path: '/equipes'
      fullPath: '/equipes/'
      preLoaderRoute: typeof AuthenticatedEquipesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/perfil_/editar': {
      id: '/_authenticated/perfil_/editar'
      path: '/perfil/editar'
      fullPath: '/perfil/editar'
      preLoaderRoute: typeof AuthenticatedPerfilEditarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/meta/$id': {
      id: '/_authenticated/meta/$id'
      path: '/meta/$id'
      fullPath: '/meta/$id'
      preLoaderRoute: typeof AuthenticatedMetaIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/equipes/nova': {
      id: '/_authenticated/equipes/nova'
      path: '/equipes/nova'
      fullPath: '/equipes/nova'
      preLoaderRoute: typeof AuthenticatedEquipesNovaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/equipes/$id/': {
      id: '/_authenticated/equipes/$id/'
      path: '/equipes/$id'
      fullPath: '/equipes/$id/'
      preLoaderRoute: typeof AuthenticatedEquipesIdIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/equipes/$id/desafio/novo': {
      id: '/_authenticated/equipes/$id/desafio/novo'
      path: '/equipes/$id/desafio/novo'
      fullPath: '/equipes/$id/desafio/novo'
      preLoaderRoute: typeof AuthenticatedEquipesIdDesafioNovoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedBuscaRoute: typeof AuthenticatedBuscaRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedDesafioTemporadaRoute: typeof AuthenticatedDesafioTemporadaRoute
  AuthenticatedDescobrirRoute: typeof AuthenticatedDescobrirRoute
  AuthenticatedDuelosRoute: typeof AuthenticatedDuelosRoute
  AuthenticatedFeedRoute: typeof AuthenticatedFeedRoute
  AuthenticatedMetasRoute: typeof AuthenticatedMetasRoute
  AuthenticatedNotificacoesRoute: typeof AuthenticatedNotificacoesRoute
  AuthenticatedNovaMetaRoute: typeof AuthenticatedNovaMetaRoute
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRoute
  AuthenticatedRankingRoute: typeof AuthenticatedRankingRoute
  AuthenticatedEquipesNovaRoute: typeof AuthenticatedEquipesNovaRoute
  AuthenticatedMetaIdRoute: typeof AuthenticatedMetaIdRoute
  AuthenticatedPerfilEditarRoute: typeof AuthenticatedPerfilEditarRoute
  AuthenticatedEquipesIndexRoute: typeof AuthenticatedEquipesIndexRoute
  AuthenticatedEquipesIdIndexRoute: typeof AuthenticatedEquipesIdIndexRoute
  AuthenticatedEquipesIdDesafioNovoRoute: typeof AuthenticatedEquipesIdDesafioNovoRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedBuscaRoute: AuthenticatedBuscaRoute,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedDesafioTemporadaRoute: AuthenticatedDesafioTemporadaRoute,
  AuthenticatedDescobrirRoute: AuthenticatedDescobrirRoute,
  AuthenticatedDuelosRoute: AuthenticatedDuelosRoute,
  AuthenticatedFeedRoute: AuthenticatedFeedRoute,
  AuthenticatedMetasRoute: AuthenticatedMetasRoute,
  AuthenticatedNotificacoesRoute: AuthenticatedNotificacoesRoute,
  AuthenticatedNovaMetaRoute: AuthenticatedNovaMetaRoute,
  AuthenticatedPerfilRoute: AuthenticatedPerfilRoute,
  AuthenticatedRankingRoute: AuthenticatedRankingRoute,
  AuthenticatedEquipesNovaRoute: AuthenticatedEquipesNovaRoute,
  AuthenticatedMetaIdRoute: AuthenticatedMetaIdRoute,
  AuthenticatedPerfilEditarRoute: AuthenticatedPerfilEditarRoute,
  AuthenticatedEquipesIndexRoute: AuthenticatedEquipesIndexRoute,
  AuthenticatedEquipesIdIndexRoute: AuthenticatedEquipesIdIndexRoute,
  AuthenticatedEquipesIdDesafioNovoRoute:
    AuthenticatedEquipesIdDesafioNovoRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
